### ISSUE TITLE
Detailed approach for implementation of N beacon 1 Group.

### ISSUE THREAD

**Issue by Aadeesh11** [CCExtractor/beacon-backend#152]
This issue (open for discussion!)  describes the detailed implementation on how to update the backend for this feature.

Current roadmap (in-order): 

- [x]  Implement data model: Group data model should be added to be able to store it in MongoDB.

```jsx
GroupModel = {  
	id, 
	shortcode //(can be used to join), 
	title //name, 
	[followers id] //list, 
	leader id //super leader (who created the group, with ability to delete the grp (TBD), 
	[beacon ids] //list.
}
```

- [x]  Update existing models,
    - [x]  Beacon model:
        - [x]  New field,  ```grpID = id of the group belongs to```.
        - [ ]  Remove the ```followers``` list, since it is same as ```group's followers list```. (TBD)
        - [ ]  Remove ```shortcode```, since joining the group is sufficient for joining the beacon. (TBD)
        - [x]  leader is not same as the group’s leader. Here leader is the one who created it, which can later be changed using ```changeLeader()``` mutation.
    - [x]  User Model:
        - [x]  New field, ```groups = [ids of all the groups the user is a part of]```.
- [x]  New mutations for creating, joining and fetching a group (changes to be done is resolvers and typedefs).
    - [x]  ```createAGroup()``` ,  fairly straightforward, creating a new group with all the fields and saving it in the DB.
    - [x]  ```joinAGroup(shortcode)```,  Add the new member to all the beacons in the group, also use pubsub to publish this change.
    - [x]  ```getGroupDetails()``` (small thing to be taken care of is populating the necessary fields before returning).
    - [ ]  nearby groups, what is a “group’s location”? (TBD).
- [ ]  Update the existing mutations, queries and subscriptions to incorporate group model.
    - [x]  Update ```me``` query.
    - [x]  Update ```createBeacon()``` and ```joinBeacon()``` mutations.
    - [ ]  Change ```beaconJoined()``` subscription to ```groupJoined()```, since the followers list is same for all the beacons in the group.

<aside>
💡 Open for further discussion!
</aside>

(TBD = To be discussed)

**Comment by aadibajpai** [comment]
I'm curious how you plan to preserve current features, eg. what would the group id be if the user just wants to join a one off beacon? 

I guess it depends if we want to make groups the primary idea of a beacon, or if we consider groups to be an extra feature.

**Comment by cfsmp3** [comment]
> I guess it depends if we want to make groups the primary idea of a beacon, or if we consider groups to be an extra feature.

I'm leaning towards all beacons belonging to one group, even if most groups (probably, who knows) will just have one.

BTW wondering in any case how this will be used in the frontend - are we going to display the location of all beacons in the group, or the closest one? What if a beacon abandons the group?

**Comment by Aadeesh11** [comment]
> I'm curious how you plan to preserve current features, eg. what would the group id be if the user just wants to join a one off beacon?
> 
> I guess it depends if we want to make groups the primary idea of a beacon, or if we consider groups to be an extra feature.

I think what can be done is that, we keep two separate lists, one containing the members (ids) of the group, and other with individual beacon under the group containing follower (ids) of the beacon. This way user can join a one off beacon w/o having to join the group necessarily.

**Comment by Aadeesh11** [comment]
> I'm leaning towards all beacons belonging to one group, even if most groups (probably, who knows) will just have one.

This sounds good!

**Comment by ItsAdityaKSingh** [comment]
> > I guess it depends if we want to make groups the primary idea of a beacon, or if we consider groups to be an extra feature.
> 
> I'm leaning towards all beacons belonging to one group, even if most groups (probably, who knows) will just have one.
> 
> BTW wondering in any case how this will be used in the frontend - are we going to display the location of all beacons in the group, or the closest one? What if a beacon abandons the group?

I did not quite get the idea of a beacon abandoning its group @cfsmp3. Like we would be showing the list of beacons contained inside a group under the group screen in which the user(group member) would get the option to join any beacon they like, or the list of beacons would be location-based?
