### ISSUE TITLE
Feature Request: A Graphql mutation to allow changing the duration of beacon once it has been created.

### ISSUE THREAD

**Issue by Aadeesh11** [CCExtractor/beacon-backend#71]
Currently, once a beacon is created we cant change is duration, to implement this (in frontend) we need a mutation to change the duration (expiresAt param of beacon). 

This would allow us to solve https://github.com/CCExtractor/beacon/issues/17.

Thanks.

**Comment by aadibajpai** [comment]
> @aadibajpai i would like to work on this issue, can you guide me as to what needs to be done.

You want to make another mutation that performs some basic checks e.g. only beacon leader should be allowed to extend time and then you simply modify the property.

**Comment by Aadeesh11** [comment]
Will try to implement it.
