### ISSUE TITLE
User should not be able to join expired beacons.

### ISSUE THREAD

**Issue by Aadeesh11** [CCExtractor/beacon-backend#73]
> Should the last(5th) be part of backend logic or frontend? 

Anything related to security / privacy / etc must be handled in the backend - you just can't trust the frontend :-)

So the backend should prevent joining an expired beacon, return some error, and then the frontend can capture that error and display it.

_Originally posted by @cfsmp3 in https://github.com/CCExtractor/beacon/issues/33#issuecomment-1001977164_

**Comment by aadibajpai** [comment]
This should be trivial to do, the only reason we didn't do this already is to use this hack while testing since we could join expired beacons. But this would be a one line fix here https://github.com/CCExtractor/beacon-backend/blob/master/graphql/resolvers.js#L119

**Comment by Aadeesh11** [comment]
I have created a pr about the changes you mentioned.
