### ISSUE TITLE
Feature Request: A Graphql mutation to deactivate the beacon on leader's request.

### ISSUE THREAD

**Issue by devansh12b2** [CCExtractor/beacon-backend#78]
Currently, once a beacon is created it cannot be deactivated but to implement the deactivation feature (in frontend ) we need this mutation.

This will allow us to solve [CCExtractor/beacon#5](https://github.com/CCExtractor/beacon/issues/5)

**Comment by Aadeesh11** [comment]
We can close this issue also.
